### ISSUE TITLE
Send image or pdf file

### ISSUE THREAD

**Issue by aziz1117** [green-api/whatsapp-api-client-js#128]
I tried to use sendFileByUrl to send image or pdf file, but I did not work for me. I am using front-end to send image or pdf file to the node.js server then I used sendFileByUrl to send the file to the whatsapp, it did not work.

Could you please help me to implement this.

**Comment by AknurKh** [comment]
Hello!
Please, make sure you execute the request as in [the example](https://github.com/green-api/whatsapp-api-client-js/blob/master/examples/SendWhatsAppFileUrl.js).

If you execute a request as in the example and receive an error, then please write to our technical support:
email - [support@greenapi.com](mailto:support@greenapi.com)
WhatsApp - https://wa.me/77273122366

**Comment by aziz1117** [comment]
@AknurKh I follow the example. Can I execute this example using localhost? 
When I execute these example I got idmessage response, but without sending anything

**Comment by AknurKh** [comment]
Yes, you can execute examples using localhost. Did you scan qr code? Are you authorized?
please write to our technical support:
email - [support@greenapi.com](mailto:support@greenapi.com)
WhatsApp - https://wa.me/77273122366

**Comment by aziz1117** [comment]
Yes I scanned qr code, I am authorized

**Comment by AknurKh** [comment]
please write your instance number to our technical support:
email - [support@greenapi.com](mailto:support@greenapi.com)
WhatsApp - https://wa.me/77273122366
