### ISSUE TITLE
sendFileByURl is not working

### ISSUE THREAD

**Issue by Sanjeevsd** [green-api/whatsapp-api-client-js#14]
1. phoneNumber is not supported, we need to add chatId, and even after adding chatId it says gives Correct ourput, but the message/attachment is not sent

/waInstance{{idInstance}}/sendFileByUrl/{{apiTokenInstance}}

**Comment by ripreal** [comment]
I've just checked and it works correctly. phoneNumber is really not supported anymore. You should always use chatId.

If you're still not receiving file messages please  let me know and provide your instanceId

Correct example of using is here:
```
const restAPI = whatsAppClient.restAPI(({
    idInstance: process.env.ID_INSTANCE,
    apiTokenInstance: process.env.API_TOKEN_INSTANCE
}))
const response = await restAPI.file.sendFileByUrl('phone_number@c.us','', "https://d2thhons2dtfkb.cloudfront.net/uploads/FaleComigo/45245_remarketing_peca4_feed_easy-resizecom.jpg", "hello.jpg");
```
