### ISSUE TITLE
Replied message not received 

### ISSUE THREAD

**Issue by Anoncomrade993** [green-api/whatsapp-api-client-js#148]
I'm currently working with the newest version of this library on npm 

After reading through the green api: 

I tried the snippet given on this  `whatsap-api-client-js` GitHub docs 

It receives messages quite alright 
But doesn't receive replied messages

**Comment by prostraction** [comment]
Hello, @Anoncomrade993 
It seems like your code is not handling quoted messages.

Please write your code snippet.
Replied message has type: `typeMessage: 'quotedMessage'` with object `quotedMessage`.
An example of this webhook provided in [documentation](https://green-api.com/en/docs/api/receiving/notifications-format/incoming-message/TextMessage/#webhook-example-body-text-quote).

You can also debug receiving messages with method ReceiveNotification using the [Postman collection](https://green-api.com/en/docs/postman-collection/) or from your [personal cabinet](https://console.green-api.com/app/api/receiveIncomingNotifications).
