### ISSUE TITLE
Indian phone number format

### ISSUE THREAD

**Issue by cullsin** [green-api/whatsapp-api-client-js#15]
Hi, 

I am Raja. I am using the WhatsApp API to send a message. For example, my number is (code)(number) -- (+91)(9886356363). Can you please suggest the same format/signature called the sendMessage() function? Also, let me know if there are any other changes required.

I am getting 466 error message on following Indian number.
`
await restAPI.message.sendMessage('9886356363@c.us', null,  "hello world")
        .then((data) => {
            res.status(200).send({ data });
        })

`

**Comment by lavahasif** [comment]
you must add like this await restAPI.message.sendMessage('[919886356363@c.us](mailto:9886356363@c.us)', null, "hello world")
